def somar(numero_1: float, numero_2: float) -> float:
    ...

def subtrair(numero_1: float, numero_2: float) -> float:
    ...

def multiplicar(numero_1: float, numero_2: float) -> float:
    ...

def dividir(numero_1: float, numero_2: float) -> float:
    ...